### ISSUE TITLE
Reloading the plugin when a scene is opened

### ISSUE THREAD

**Issue by HungryProton** [protongraph/protongraph#19]
If there is an open scene containing a ConceptGraph node, reloading the plugin doesn't work

**Comment by Muzz** [comment]
I can't get it to reload the scene regardless of if concept graph is open in a scene or not. Having to restart godot to make this work feels bad 🤔

**Comment by HungryProton** [comment]
Strange, do you have any error messages in the console when you try to reload the addon?

**Comment by Muzz** [comment]
I don't. 

The behavior is that it will load new scripts i add, but not reload scripts that are already in memory. 

No errors. This is using the plugin reloader addon btw.

**Comment by Banbury** [comment]
This is a problem I had, too, when writing plugins. AFAIK this has never been fixed, and I gave up on developing plugins for Godot.

**Comment by Muzz** [comment]
Aaah yeah for now i'm just using the ctrl+shift+q command to exit to project manager and reload the whole thing. it's annoying but workable right now.

**Comment by HungryProton** [comment]
Closing as this is no longer a Godot add-on
