### ISSUE TITLE
Merge mesh tree together

### ISSUE THREAD

**Issue by fire** [protongraph/protongraph#45]
https://github.com/godot-extended-libraries/scene_merge

Don't have the bandwidth to copy to GDNative. Thoughts on porting?

**Comment by HungryProton** [comment]
What does it do exactly? Takes all the meshes and merge them into a single surface?

**Comment by fire** [comment]
Yes.

**Comment by HungryProton** [comment]
Done in 3e259073b97afe27c5340d37f3c88a6dc7633ef2, but I just used the surface tool directly and not the library you linked. Although, the materials are ignored for now, this might need some extra work later.
