### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by nonunknown** [protongraph/protongraph#84]
**Godot**
3.2.2 stable

**OS**
ubuntu 20.04

**Issue Description**
When installing icons doesnt show as in documentation shows

original:
![Screenshot from 2020-07-11 17-43-44](https://user-images.githubusercontent.com/58845030/87233489-451d0400-c39e-11ea-8c74-8d95f9355238.png)

docs:
![](https://user-images.githubusercontent.com/52043844/81483879-a2cb8d80-9241-11ea-9aa8-973b3ffdf053.png)

**Comment by HungryProton** [comment]
It happens to me sometimes but restarting the editor is usually enough. Not sure why it happens in the first place though.
I'll look into it as soon as I start with the sync plugin that's supposed to replace this.

**Comment by HungryProton** [comment]
Closing, as this is no longer a Godot add-on.
