### ISSUE TITLE
Error moving path points on camp example

### ISSUE THREAD

**Issue by NewNodeGames** [protongraph/protongraph#86]
When I try to move a point on path fence the editor goes unresponsive and debug console prints repeatdly an error.
Godot version: 3.2.2

**Comment by HungryProton** [comment]
Can you copy/paste the exact error please? I can't really help you with this little amount of information

**Comment by NewNodeGames** [comment]
ERROR: Disconnecting nonexistent signal 'changed', slot: 43763: mesh_changed.
core/object.cpp:1573
the error prints so fast on loop

**Comment by HungryProton** [comment]
Seems like a recent issue, it used to work before, not sure yet if this comes from the latest 3.2.2 version or if a patch on ConceptGraph broke this at some point. I'll investigate.

**Comment by NewNodeGames** [comment]
Same happens trying with 3.2.1 and 3.1.1 versions

**Comment by HungryProton** [comment]
Closing as this is no longer a Godot add-on
