### ISSUE TITLE
Regenerate mesh at runtime?

### ISSUE THREAD

**Issue by chances** [protongraph/protongraph#98]
I've saved an instance of `ConceptGraph3D` in its own scene, then instanced it from script, and added a new `Path` input. Then, I call the graph's `generate` function.

```gdscript
var a = get_wire_points($poles/pole_transmission)
var b = get_wire_points($poles/pole_transmission2)
var wire = wire_scn.instance()
var path = Path.new()
path.name = "Path"
var a1 = $poles/pole_transmission.to_global(a[0].translation)
var b1 = $poles/pole_transmission2.to_global(b[0].translation)
path.curve.add_point(a1)
path.curve.add_point(b1)
path.curve.set_point_tilt(0, deg2rad(5))
$wires.add_child(wire)
wire.get_node("Input").add_child(path)
wire.clear_output()
wire.generate(true)
```

However, I don't see any new geometry in the scene at runtime. What needs to change in my script?

**Comment by HungryProton** [comment]
Runtime generation has always been planned but it's currently disabled.
There's two possible options though:

- Either replace the two final lines of your code by this:
``` gdscript
wire.reload_template()
wire.clear_output()
wire._template.generate(true)
```

- Or remove the editor checks in concept_graph.gd and keep your original code. There's one in `enter_tree` and another one in `generate`.

**Comment by chances** [comment]
Unfortunately, calling `reload_template` at runtime modifies my scene and renders the Concept Graph Editor UI underneath my UI. I'm trying to narrow down where this happens; any pointers?

**Comment by HungryProton** [comment]
The ConceptGraph node is a control node (it extends from GraphEdit) so if it's under another control it will show up on screen. `load_from_file` will load the node graph in memory and run the generation from this data so you can't skip this part.

The results are stored under the `Output` node (right next to the `Input` node). Maybe you can just hide the ConceptGraph node and move the results somewhere else on the tree each time you regenerate an output?

**Comment by HungryProton** [comment]
Closing as this is no longer a Godot add-on.
